id: PB88BBCCC
initial_creation_type: input
source_metadata:
  work_id: http://purl.bdrc.io/resource/WA23259
  instance_id: http://purl.bdrc.io/resource/IE23259
  collection_id: http://purl.bdrc.io/resource/PR0ET010
  language_id: http://purl.bdrc.io/resource/LangBo
  title:
    bo:
    - རི་ཆོས་མཚམས་ཀྱི་ཞལ་གདམས།
  alt_title: {}
  author: http://purl.bdrc.io/resource/P649
  publisher: Various
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  volumes:
    2906cb704a88431d9b9a60373b87e9f3:
      title: ༄༅།་།སྲིད་པའི་འཇིགས་པ་ལས་སྐྱོབས་ཤིང༌།་།རྣམ་གྲོལ་བགྲོད་པའི་ལམ་གཅིག་པུ།་།ལུང་རྟོགས་གཉིས་བསྡུས་ཞི་བསིལ་ཆོས།་།གུས་པའི་ཕྱག་གི་ཡུལ
      volume_number: 1
      base_file: UT23259_001_0001.txt
      reference: http://purl.bdrc.io/resource/VL27CCB7C9EB6048B4
      image_group: null
      quality: null
  reproductionOf:
  - http://purl.bdrc.io/resource/MW23259
  - http://purl.bdrc.io/resource/W23259
created_at: '2021-12-22T11:08:29.626699'
last_modified_at: '2021-12-22T11:08:29.626706'
